name: PotSG
main: me.weebo.PotionSG
version: 1.0
author: m69, REAS0NS
softdepend: [Multiverse-Core]
commands:
  host:
  build:
  setlobbyspawn:
  arena:
  cancel:
  start:
    aliases: [forcestart]
  setslots:
  gameinfo:
    aliases: [gi, info, help]
  freeze:
    aliases: [ss, screenshare]